### ISSUE TITLE
Uncaught TYPO3 Exception in BE Module in T3 v8

### ISSUE THREAD

**Issue by lsascha** [undkonsorten/registeraddress_logger#3]
I received an uncaught TYPO3 Exception when accessing the Backend Module in TYPO3 v8.
`PHP Warning: class_parents(): Class Address does not exist and could not be loaded in /var/www/html/typo3/sysext/extbase/Classes/Persistence/Generic/Mapper/DataMapper.php line 282`

I think this is a "bug?" in the TYPO3 annotation parser that it does not understand imported namespaces so it needs full qualified namespace in annotations.

Should be fixed by Pullrequest #2

**Comment by Starkmann** [comment]
Fixed in version 1.0.1
