### ISSUE TITLE
Backendmodule wont work!

### ISSUE THREAD

**Issue by opaque01** [undkonsorten/registeraddress_logger#5]
Error message in Backend (TYPO3 v 8.7.13):
Sorry, the requested view was not found.

The technical reason is: No template was found. View could not be resolved for action "list" in class "Undkonsorten\RegisteraddressLogger\Controller\LogentryController".

lg opaque

**Comment by opaque01** [comment]
Solution: Move the folders "Layout and Templates" to Private!

**Comment by Starkmann** [comment]
You just have to add the static ts.

**Comment by opaque01** [comment]
Ah ok, thanks.
