### ISSUE TITLE
Blocks Backend-Login

### ISSUE THREAD

**Issue by ULinn** [undkonsorten/registeraddress_logger#6]
Using Typo3 8.7.13, registeraddress_logger 1.01 and register_address 1.0.13 I can't login in the backend anymore. Login screen as usual, after klicking on login-button, I get the following errror:

Oops, an error occurred!
[module-tools_RegisteraddressLoggerLogentry] The option "source" is required and must not be empty 

Deleting extension-folder and entry in LocalConfiguration for both register_address and registeraddress_logger doesnt solve the problem.

**Comment by ULinn** [comment]
Can be solved by updating typo3 to 8.7.14

**Comment by ULinn** [comment]
Sorry, problem disappeared after the update, but i there again. No access to backend after the login-screen witht the above error-message.

**Comment by ULinn** [comment]
Additional Info: 
- "Clear all cache" in Install tool does not solve the problem.
- Frontend seems to be OK

**Comment by ULinn** [comment]
The log says:

`Uncaught TYPO3 Exception: #1460976566: [module-tools_RegisteraddressLoggerLogentry] The option "source" is required and must not be empty | InvalidArgumentException thrown in file /html/typo3_src-8.7.14/typo3/sysext/core/Classes/Imaging/IconProvider/SvgIconProvider.php in line 48.`

**Comment by Starkmann** [comment]
Can not reproduce this.

Can you post the configuration under
```$GLOBALS['TBE_MODULES']['_configuration']['tools_RegisteraddressLoggerLogentry']```

**Comment by ULinn** [comment]
Sorry, don't know where to find this information ...

**Comment by Starkmann** [comment]
In Backend click "Configuration" then choose on top "$GLOBALS['TBE_MODULES']" and navigate to the right position (see above)

**Comment by ULinn** [comment]
```
tools_RegisteraddressLoggerLogentry
access = user,group
configureModuleFunction
0 = TYPO3\CMS\Core\Utility\ExtensionManagementUtility
1 = configureModule
extensionName = RegisteraddressLogger
icon = EXT:registeraddress_logger/Resources/Public/Icons/user_mod_logentry.svg
labels = LLL:EXT:registeraddress_logger/Resources/Private/Language/locallang_logentry.xlf
name = tools_RegisteraddressLoggerLogentry
vendorName = Undkonsorten
```

**Comment by Starkmann** [comment]
This is exactly what I have here.

Do you used composer install?

Is your extension Folder named correctly? "registeraddress_logger"

**Comment by ULinn** [comment]
I don't know, what "composer install" is. I guess I did upload the .zip file in the backend.

The folder is called "registeraddress_logger-master" (not changed by me)

**Comment by Starkmann** [comment]
You have to rename "registeraddress_logger-master" to "registeraddress_logger"

**Comment by ULinn** [comment]
seems to work, but can't test completly in production while sending tons of newsletters ...
Thank you!

**Comment by Starkmann** [comment]
You are welcome.
