### ISSUE TITLE
Direct Mail Adress Import fails

### ISSUE THREAD

**Issue by ULinn** [undkonsorten/registeraddress_logger#7]
Using Direct Mails function to import a .csv recipients list I get the following error:

Oops, an error occurred!
An exception occurred while executing 'SELECT `uid`, `www`, `email`, `image`, `description`, `categories`, `log`, `module_sys_dmail_category`, `deleted`, `t3ver_wsid` FROM `tt_address` WHERE `uid` = ?' with params [308956]: Unknown column 'log' in 'field list'

The csv-import is important to add recipients who accepted GDPR offline.

**Comment by ULinn** [comment]
More detailed:

Uncaught TYPO3 Exception: An exception occurred while executing 'SELECT `uid`, `www`, `email`, `image`, `description`, `categories`, `log`, `module_sys_dmail_category`, `deleted`, `t3ver_wsid` FROM `tt_address` WHERE `uid` = ?' with params [308961]:

Unknown column 'log' in 'field list' | Doctrine\DBAL\Exception\InvalidFieldNameException thrown in file /html/typo3_src-8.7.14/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php in line 71

**Comment by Starkmann** [comment]
Should be fixed in version 1.0.2

**Comment by ULinn** [comment]
Great, thank you. Works. You made my Day!
